import type { NextConfig } from "next";

const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH ?? ''

const nextConfig: NextConfig = {
  output: 'export',
  basePath: BASE_PATH,
  images: {
    loader: 'custom',
    loaderFile: './lib/imageLoader.ts',
    // Aligned with the WIDTHS ladder pre-generated by scripts/optimize-images.mjs
    // so srcset only requests widths we actually build.
    deviceSizes: [640, 1080, 1600],
    imageSizes: [384],
  },
};

export default nextConfig;
