// GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Regenerated on every `npm run dev` and `npm run build`.

type ImageDimensions = { width: number; height: number }

const imageDimensions: Record<string, ImageDimensions> = {
  '/images/black-and-grey/IMG_8817.jpg': { width: 1320, height: 1597 },
  '/images/black-and-grey/IMG_8862.jpg': { width: 1320, height: 1295 },
  '/images/black-and-grey/IMG_8863.jpg': { width: 1320, height: 1355 },
  '/images/black-and-grey/IMG_8864.jpg': { width: 1306, height: 1632 },
  '/images/black-and-grey/IMG_8865.jpg': { width: 1320, height: 1626 },
  '/images/black-and-grey/IMG_8867.jpg': { width: 1320, height: 1644 },
  '/images/colour-tattoo/IMG_8806.JPG': { width: 1320, height: 1315 },
  '/images/colour-tattoo/IMG_8807.JPG': { width: 1320, height: 1635 },
  '/images/colour-tattoo/IMG_8810.JPG': { width: 1320, height: 1629 },
  '/images/colour-tattoo/IMG_8822.JPG': { width: 1320, height: 1591 },
  '/images/colour-tattoo/IMG_8828.JPG': { width: 1320, height: 1248 },
  '/images/colour-tattoo/IMG_8829.JPG': { width: 1320, height: 1305 },
  '/images/colour-tattoo/IMG_8830.JPG': { width: 1320, height: 1421 },
  '/images/colour-tattoo/IMG_8839.JPG': { width: 1320, height: 1629 },
  '/images/colour-tattoo/IMG_8842.JPG': { width: 1320, height: 1579 },
  '/images/colour-tattoo/IMG_8843.JPG': { width: 1320, height: 1449 },
  '/images/colour-tattoo/IMG_8844.JPG': { width: 1320, height: 1408 },
  '/images/colour-tattoo/IMG_8850.jpg': { width: 1320, height: 1297 },
  '/images/fine-line/IMG_8803.JPG': { width: 1320, height: 1319 },
  '/images/fine-line/IMG_8811.JPG': { width: 1320, height: 1312 },
  '/images/fine-line/IMG_8814.JPG': { width: 1320, height: 1495 },
  '/images/fine-line/IMG_8819.JPG': { width: 1310, height: 1630 },
  '/images/fine-line/IMG_8826.JPG': { width: 1320, height: 1239 },
  '/images/fine-line/IMG_8827.JPG': { width: 1303, height: 1281 },
  '/images/fine-line/IMG_8834.JPG': { width: 1320, height: 1325 },
  '/images/fine-line/IMG_8835.JPG': { width: 1320, height: 1312 },
  '/images/fine-line/IMG_8841.JPG': { width: 1320, height: 1551 },
  '/images/fine-line/IMG_8848.JPG': { width: 1320, height: 1311 },
  '/images/fine-line/IMG_8858.jpg': { width: 1320, height: 1503 },
  '/images/fine-line/IMG_8859.jpg': { width: 1320, height: 1607 },
  '/images/floral/IMG_8820.jpg': { width: 1320, height: 1364 },
  '/images/floral/IMG_8824.jpg': { width: 1320, height: 1639 },
  '/images/floral/IMG_8825.jpg': { width: 1320, height: 1368 },
  '/images/floral/IMG_8882.jpg': { width: 1320, height: 1287 },
  '/images/floral/IMG_8883.jpg': { width: 1320, height: 1278 },
  '/images/floral/IMG_8885.jpg': { width: 1320, height: 1622 },
  '/images/logo-main.png': { width: 211, height: 231 },
  '/images/micro-realism/IMG_8808.jpg': { width: 1320, height: 1654 },
  '/images/micro-realism/IMG_8809.jpg': { width: 1320, height: 1637 },
  '/images/micro-realism/IMG_8812.jpg': { width: 1320, height: 1424 },
  '/images/micro-realism/IMG_8813.jpg': { width: 1320, height: 1616 },
  '/images/micro-realism/IMG_8860 2.jpg': { width: 1320, height: 1295 },
  '/images/micro-realism/IMG_8881.jpg': { width: 1320, height: 1276 },
  '/images/old-school/IMG_8851.jpg': { width: 1298, height: 1623 },
  '/images/old-school/IMG_8852.jpg': { width: 1320, height: 1632 },
  '/images/old-school/IMG_8853.jpg': { width: 1320, height: 1626 },
  '/images/old-school/IMG_8854.jpg': { width: 1320, height: 1287 },
  '/images/old-school/IMG_8855.jpg': { width: 1320, height: 1305 },
  '/images/old-school/IMG_8856.jpg': { width: 1299, height: 1315 },
  '/images/profile-pic.png': { width: 515, height: 675 },
}

/** Falls back to a square so an unlisted image still reserves space. */
export function aspectRatioOf(src: string): string {
  const d = imageDimensions[src]
  return d ? `${d.width} / ${d.height}` : '1 / 1'
}
